spring:
  application:
    name: eureka-peer1
server:
  port: 8762
security:
  user:
    name: root
    password: root
eureka:
  instance:
    hostname: eureka-peer1
  client:
    service-url:
      defaultZone: http://root:root@eureka-master:8761/eureka
    fetch-registry: true
    register-with-eureka: true





